#include <catch2/catch_test_macros.hpp>
#include <string>

#include "command_model_parity_cases.hpp"
#include "magda/agents/command_model.hpp"

// Locks the hand-written C++ command-model backend to the Python POC reference:
// every one of the committed 102 test cases must produce byte-identical DSL to
// the float32 Python forward (prototypes/command-model-poc/, issue #1827).
// Regenerate the fixture + weights via model/export_cpp.py.

using magda::CommandModel;
using namespace magda::cmdmodel::test;

TEST_CASE("Command model reproduces the Python DSL byte-for-byte", "[agents][command_model]") {
    CommandModel model;
    int mismatches = 0;
    for (int i = 0; i < kNumParityCases; ++i) {
        const auto& c = kParityCases[i];
        std::string got = model.generate(c.input);
        if (got != c.expected) {
            ++mismatches;
            UNSCOPED_INFO("input:    " << c.input);
            UNSCOPED_INFO("expected: " << c.expected);
            UNSCOPED_INFO("got:      " << got);
        }
        CHECK(got == std::string(c.expected));
    }
    CHECK(mismatches == 0);
    CHECK(kNumParityCases == 111);
}

// The tokenizer is a hand-maintained mirror of dataset/tagging.py:tokenize.
// The parity fixture above contains no number-glued-to-unit input, so it cannot
// catch drift in the glued-unit split added for #1847 ("-6db" -> "-6", "db").
// Expected token lists below are generated by the Python reference.
TEST_CASE("Command model tokenizer mirrors the Python reference", "[agents][command_model]") {
    struct Probe {
        const char* input;
        std::vector<std::string> expected;
    };
    const std::vector<Probe> probes = {
        // split: number + whitelisted unit
        {"bring the bass down to -6db", {"bring", "the", "bass", "down", "to", "-6", "db"}},
        {"put an 8bar clip on Bass", {"put", "an", "8", "bar", "clip", "on", "Bass"}},
        {"make it 2.5bars long", {"make", "it", "2.5", "bars", "long"}},
        {"move 4st up", {"move", "4", "st", "up"}},
        // NOT split: already separate, grid phrase, pitch, alias, bare number
        {"set Bass volume to -6 dB", {"set", "Bass", "volume", "to", "-6", "dB"}},
        {"quantize the keys to 16ths", {"quantize", "the", "keys", "to", "16ths"}},
        {"select every C3 on the bass track",
         {"select", "every", "C3", "on", "the", "bass", "track"}},
        {"add @pro_q_3 to Keys", {"add", "@pro_q_3", "to", "Keys"}},
        {"transpose 12 semitones", {"transpose", "12", "semitones"}},
        {"clip 3 on Vocals", {"clip", "3", "on", "Vocals"}},
        {"pan 0.5", {"pan", "0.5"}},
    };

    CommandModel model;
    for (const auto& p : probes) {
        UNSCOPED_INFO("input: " << p.input);
        CHECK(model.predict(p.input).tokens == p.expected);
    }
}
