"""Export the trained router to C++ inference artifacts.

One-off codegen, mirroring command-model-poc/model/export_cpp.py: reads the
checkpoint + maps and emits the float32 weights, the vocab/label lookup tables
and a parity fixture into the app tree, so magda/agents/router_model.* runs the
model offline with zero new dependencies.

    ./.venv/bin/python -m router.export_cpp

Regenerate whenever the checkpoint or maps change. Outputs are committed.
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from router.reference import load_reference  # noqa: E402
from router.text import MAX_LEN  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
POC = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(POC))
ARTIFACTS = os.path.join(POC, "artifacts")

AGENTS_DIR = os.path.join(REPO, "magda", "agents")
TESTS_DIR = os.path.join(REPO, "tests")


def _fmt(x: float) -> str:
    """9 significant digits round-trips a float32 exactly."""
    return "%.9g" % float(x)


def _wrap(values, per_line: int) -> str:
    return "\n".join("    " + ", ".join(values[i:i + per_line]) + ","
                     for i in range(0, len(values), per_line))


def _float_array(name: str, flat) -> str:
    return f"const float {name}[] = {{\n{_wrap([_fmt(v) for v in flat], 200)}\n}};\n\n"


def _cstr(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _string_array(name: str, items) -> str:
    return f"const char* const {name}[] = {{\n{_wrap([_cstr(s) for s in items], 12)}\n}};\n\n"


def export():
    vocab, labels, sd, predict = load_reference(ARTIFACTS)

    id2tok = [None] * len(vocab)
    for tok, i in vocab.items():
        id2tok[i] = tok
    assert all(t is not None for t in id2tok), "vocab ids must be dense"

    embed = sd["embed.weight"].shape[1]
    hidden = sd["b1.0.weight"].shape[0]

    # ---- data header -----------------------------------------------------
    hpp = f"""// GENERATED by prototypes/router-model-poc/router/export_cpp.py — do not edit.
// Float32 weights + lookup tables for the on-device ConsoleIntent router.
#pragma once

namespace magda::routermodel::data {{

inline constexpr int kVocabSize = {len(vocab)};
inline constexpr int kEmbed = {embed};
inline constexpr int kHidden = {hidden};
inline constexpr int kNumLabels = {len(labels)};
inline constexpr int kMaxLen = {MAX_LEN};
inline constexpr int kKernel = 3;

extern const float kEmbedWeight[];  // [kVocabSize * kEmbed]
extern const float kB1Weight[];     // [kHidden * kEmbed * kKernel]
extern const float kB1Bias[];       // [kHidden]
extern const float kB2Weight[];     // [kHidden * kHidden * kKernel]
extern const float kB2Bias[];       // [kHidden]
extern const float kB3Weight[];     // [kHidden * kHidden * kKernel]
extern const float kB3Bias[];       // [kHidden]
extern const float kHeadWeight[];   // [kNumLabels * kHidden]
extern const float kHeadBias[];     // [kNumLabels]

extern const char* const kVocab[];   // [kVocabSize] id -> token (UTF-8)
extern const char* const kLabels[];  // [kNumLabels] id -> ConsoleIntent token

}}  // namespace magda::routermodel::data
"""
    with open(os.path.join(AGENTS_DIR, "router_model_data.hpp"), "w") as f:
        f.write(hpp)

    # ---- data source -----------------------------------------------------
    def flat(name):
        return sd[name].detach().flatten().tolist()

    cpp = ["// GENERATED by prototypes/router-model-poc/router/export_cpp.py — do not edit.\n",
           "// clang-format off\n",  # keep the weight blob compact (LOC policy)
           '#include "router_model_data.hpp"\n\n',
           "namespace magda::routermodel::data {\n\n"]
    cpp.append(_float_array("kEmbedWeight", flat("embed.weight")))
    cpp.append(_float_array("kB1Weight", flat("b1.0.weight")))
    cpp.append(_float_array("kB1Bias", flat("b1.0.bias")))
    cpp.append(_float_array("kB2Weight", flat("b2.0.weight")))
    cpp.append(_float_array("kB2Bias", flat("b2.0.bias")))
    cpp.append(_float_array("kB3Weight", flat("b3.0.weight")))
    cpp.append(_float_array("kB3Bias", flat("b3.0.bias")))
    cpp.append(_float_array("kHeadWeight", flat("head.weight")))
    cpp.append(_float_array("kHeadBias", flat("head.bias")))
    cpp.append(_string_array("kVocab", id2tok))
    cpp.append(_string_array("kLabels", labels))
    cpp.append("}  // namespace magda::routermodel::data\n")
    with open(os.path.join(AGENTS_DIR, "router_model_data.cpp"), "w") as f:
        f.write("".join(cpp))

    # ---- parity fixture --------------------------------------------------
    with open(os.path.join(POC, "eval", "testset.jsonl"), encoding="utf-8") as f:
        rows = [json.loads(l) for l in f if l.strip()]
    cases, wrong = [], 0
    for r in rows:
        got = predict(r["input"])
        wrong += got != r["label"]
        cases.append((r["input"], got))

    fx = ["// GENERATED by prototypes/router-model-poc/router/export_cpp.py — do not edit.\n",
          f"// Reference labels from the Python float32 forward over the committed\n"
          f"// {len(cases)}-case test set. The C++ backend must reproduce each one exactly.\n",
          "#pragma once\n\n",
          "namespace magda::routermodel::test {\n\n",
          "struct ParityCase { const char* input; const char* expected; };\n\n",
          "inline const ParityCase kParityCases[] = {\n"]
    for inp, out in cases:
        fx.append(f"    {{{_cstr(inp)}, {_cstr(out)}}},\n")
    fx.append("};\n\n")
    fx.append(f"inline constexpr int kNumParityCases = {len(cases)};\n\n")
    fx.append("}  // namespace magda::routermodel::test\n")
    with open(os.path.join(TESTS_DIR, "router_model_parity_cases.hpp"), "w") as f:
        f.write("".join(fx))

    kb = (len(vocab) * embed + hidden * embed * 3 + hidden * hidden * 6
          + len(labels) * hidden) * 4 / 1024
    print(f"exported: {len(vocab)} vocab, {len(labels)} labels, ~{kb:.0f} KB float32")
    print(f"parity fixture: {len(cases)} cases ({wrong} of which the model gets wrong "
          f"vs gold — the fixture locks behaviour, not correctness)")


if __name__ == "__main__":
    export()
