"""Simplified-Chinese template bank (same POOLS/TEMPLATES contract as seeds_en).

Like Japanese, Chinese is tokenized one codepoint per token, so these expand to
character sequences. Fullwidth punctuation (，。？) falls in the symbol ranges
of router/text.py and is dropped, matching the C++ tokenizer.
"""
from __future__ import annotations

POOLS = {
    "track": ["贝斯", "鼓", "主音", "铺底", "人声", "底鼓", "军鼓", "踩镲",
              "键盘", "吉他", "弦乐", "合成器", "打击乐", "低音"],
    "inst": ["钢琴", "贝斯", "吉他", "合成器", "电钢", "风琴", "弦乐", "铺底"],
    "key": ["C大调", "A小调", "D小调", "F大调", "G小调", "E小调", "降B大调"],
    "genre": ["爵士", "蓝调", "浩室", "科技舞曲", "lofi", "新灵魂乐", "放克",
              "trap", "氛围", "摇滚", "流行", "鼓打贝斯", "disco"],
    "mood": ["黑暗的", "梦幻的", "忧伤的", "史诗的", "放松的", "温暖的"],
    "param": ["滤波器截止频率", "截止频率", "共振", "音量", "声像", "混响发送",
              "失真", "延迟量"],
    "shape": ["正弦", "三角", "锯齿", "方波", "随机"],
    "n": ["1", "2", "4", "8", "16"],
    "bar": ["1", "2", "3", "5", "9"],
    "scene": ["1", "2", "3", "4", "前奏", "主歌", "副歌", "drop"],
    # Shared across classes on purpose — see the note in seeds_en.POOLS.
    "section": ["前奏", "主歌", "副歌", "过渡段", "drop", "尾奏", "间奏",
                "第二段主歌"],
    "drumpart": ["底鼓", "军鼓", "踩镲", "叮叮镲", "拍手", "嗵鼓", "打击乐"],
    "plugin": ["@serum", "@vital", "@ott", "@pro_q_3", "@valhalla", "@1176"],
    "colour": ["红色", "蓝色", "绿色", "橙色", "紫色", "黄色"],
    "db": ["-3", "-6", "-9", "-12", "0"],
    "bpm": ["90", "120", "128", "140", "160", "174"],
}

TEMPLATES = {
    "COMMAND": [
        "创建一个{track}轨道",
        "新建{track}轨",
        "删除{track}轨道",
        "把{track}重命名为{inst}",
        "静音{track}",
        "solo {track}轨道",
        "在{track}上加{plugin}",
        "给{track}轨道加{plugin}",
        "把{track}的音量设为{db}dB",
        "把{track}轨道改成{colour}",
        "把{track}和{drumpart}编组",
        "在{track}轨上加一个{n}小节的片段",
        "删除选中的片段",
        "把{track}的音符量化到十六分",
        "把{track}升{n}个半音",
        "把速度设为{bpm}",
        "在{track}轨道上创建一个机架",
        "把{track}声像推到左边",
        "把片段重命名为{genre}循环",
        "取消{track}的静音",
    ],
    "MUSIC": [
        "给我一个{key}的和弦进行",
        "来一段{genre}风格的进行",
        "{key}里有哪些和弦可以用",
        "写一个{mood}和弦进行",
        "做一个{n}小节的和弦循环，调性是{key}",
        "帮这段旋律配和声",
        "写一段{key}的旋律",
        "推荐几个{mood}和弦",
        "重新配和声",
        "给个贝斯线的想法",
        "延长这个进行",
        "这是什么调",
        "{genre}常用的和弦有哪些",
        "写一段{mood}{genre}进行",
        "{section}用什么和弦",
        "{section}的和声有什么想法",
        "重做一下{section}的和弦",
    ],
    "BOTH": [
        "创建一个{inst}轨道并写一段{genre}和弦进行",
        "新建{inst}轨并放一段{mood}进行",
        "在{track}轨上加一条{genre}贝斯线",
        "在{track}轨上放一个{n}小节的{genre}循环",
        "在{track}轨道上写{key}的和弦",
        "创建{track}轨道并加一段{genre}旋律",
        "给{track}轨加一段旋律",
        "新建一个{inst}轨道并写{n}小节的进行",
    ],
    "AUTOMATION": [
        "用{shape}把{param}自动化{n}个小节",
        "在{param}上画一条{shape}LFO",
        "创建一个{n}小节的{param}自动化片段",
        "让{param}在{n}小节内上升",
        "最后{n}小节音量淡出",
        "给{track}的音量加颤音",
        "把选中的自动化片段移到第{bar}小节",
        "循环这个自动化片段",
        "清除{track}轨道的自动化",
        "把自动化片段改成{n}小节",
        "让{param}从0变到1，用{n}个小节",
        "复制这个自动化片段",
        "在{section}里把{param}慢慢打开",
        "清掉{section}的自动化曲线",
    ],
    "DRUM": [
        "写一个{genre}风格的鼓点",
        "做一个{bpm}的{genre}律动",
        "在结尾加一个过门",
        "把{drumpart}打得更密一些",
        "四踩底鼓",
        "在{drumpart}上加鬼音",
        "把鼓人性化一点",
        "给{drumpart}加摇摆感",
        "来个碎拍",
        "把鼓的节奏简化",
        "在反拍加{drumpart}",
        "写一个{n}小节的{genre}鼓点",
        "做一个{bpm}的鼓循环",
        "让{drumpart}走十六分",
        "写{section}的鼓",
        "{section}把{drumpart}去掉",
        "{section}的鼓打密一点",
    ],
    "MIXING": [
        "为什么我的混音听起来很浑浊",
        "我的增益结构怎么样",
        "低频是不是太重了",
        "这个混音要改哪里",
        "分析一下我的混音",
        "有没有地方削波了",
        "立体声宽度怎么样",
        "{track}母线要不要压缩",
        "混音听着很刺耳，怎么办",
        "给我一些混音建议",
        "检查一下电平",
        "{track}是不是太响了",
        "还有多少余量",
        "混音平衡吗",
        "什么盖住了{track}",
        "{track}的音量平衡怎么样",
        "{track}和{drumpart}打架了",
        "怎么把混音做得更像{genre}",
        "看看低频和高频的平衡",
        "{track}的均衡这样调对吗",
        "总线的响度是多少",
        "有没有相位问题",
        "怎么把{track}提到前面来",
        "{track}需要压缩吗",
        "混音转单声道就散了",
        "{section}里{track}被埋掉了",
        "{section}听起来比别的地方单薄",
    ],
    "SESSION": [
        "启动场景{scene}",
        "播放场景{scene}",
        "停止所有片段",
        "停止{track}的片段",
        "录制一个新场景",
        "开始会话",
        "停止会话",
        "把{track}轨道设为录音待命",
        "把场景{scene}排入队列",
        "全部停止",
        "触发{track}轨的片段",
        "循环场景{scene}",
        "切换到场景{scene}",
        "准备下一个场景",
        "把{track}的片段排队",
        "开始录音",
        "停止场景{scene}",
        "取消{track}轨道的录音待命",
        "把我刚才弹的录成一个场景",
    ],
}
