"""English template bank: one list of `{slot}` phrasings per ConsoleIntent.

Every language module in this package exposes the same two names (POOLS,
TEMPLATES) so generate.py can treat them uniformly. Templates are expanded
combinatorially against POOLS, which is where the volume comes from — the
phrasings carry the *shape* of a request, the pools carry the surface variety.

Boundary cases are drawn deliberately, because they are where a coarse router
actually earns its keep:
  MUSIC vs BOTH   — "write a jazz progression" (content only) vs "create a
                    piano track with a jazz progression" (content + structure).
  COMMAND vs DRUM — "quantize the drums to 1/16" is a DSL edit; "make the hats
                    busier" is pattern authoring.
  COMMAND vs AUTOMATION — "set the volume to -6 dB" is a one-shot value;
                    "fade the volume out over 4 bars" is a curve.
"""
from __future__ import annotations

POOLS = {
    "track": ["bass", "drums", "lead", "pads", "vocals", "kick", "snare",
              "hats", "keys", "guitar", "strings", "synth", "perc", "sub",
              "reese bass", "top loop", "vox", "arp", "pluck", "master"],
    "inst": ["piano", "bass", "guitar", "synth", "rhodes", "organ", "strings",
             "pad", "lead", "keys"],
    "key": ["C major", "A minor", "D minor", "F major", "G minor", "E minor",
            "Bb major", "Eb major", "F# minor", "C# minor", "D dorian",
            "A mixolydian", "G lydian", "E phrygian"],
    "genre": ["jazz", "blues", "house", "techno", "lo-fi", "neo-soul",
              "gospel", "funk", "trap", "ambient", "rock", "pop", "bossa nova",
              "drum and bass", "garage", "disco", "afrobeat", "reggaeton"],
    "mood": ["dark", "dreamy", "uplifting", "melancholic", "epic", "chill",
             "tense", "warm", "moody", "hopeful"],
    "param": ["filter cutoff", "cutoff", "resonance", "volume", "pan",
              "reverb send", "delay mix", "drive", "wet level", "the low pass"],
    "shape": ["sine", "triangle", "saw", "square", "ramp", "exponential",
              "logarithmic", "random"],
    "n": ["1", "2", "4", "8", "16"],
    "bar": ["1", "2", "3", "5", "9", "17"],
    "scene": ["1", "2", "3", "4", "intro", "verse", "chorus", "drop"],
    # Song sections are shared vocabulary. They used to appear only in SESSION's
    # scene pool, which turned "chorus" into a spurious SESSION marker and sent
    # "ideas for the pre chorus harmony" to the session agent. Any word that can
    # occur in several classes has to be *generated* in several classes.
    "section": ["intro", "verse", "chorus", "bridge", "drop", "outro",
                "pre chorus", "breakdown", "second verse", "last chorus"],
    "drumpart": ["kick", "snare", "hats", "hi hats", "ride", "clap", "toms",
                 "percussion", "shaker", "crash"],
    "plugin": ["@serum", "@vital", "@ott", "@pro_q_3", "@valhalla", "@1176",
               "@diva", "@compressor", "@reverb", "@delay"],
    "colour": ["red", "blue", "green", "orange", "purple", "yellow"],
    "db": ["-3", "-6", "-9", "-12", "0", "3"],
    "bpm": ["90", "120", "128", "140", "160", "174"],
}

TEMPLATES = {
    "COMMAND": [
        "create a {track} track",
        "add a new {track} track",
        "make a {inst} track",
        "delete the {track} track",
        "rename {track} to {inst}",
        "mute the {track}",
        "solo the {track} track",
        "unmute {track}",
        "add {plugin} to the {track} track",
        "put {plugin} on {track}",
        "set the {track} volume to {db} dB",
        "turn the {track} down by {db} dB",
        "pan the {track} hard left",
        "make the {track} track {colour}",
        "colour {track} {colour}",
        "group the {track} and {drumpart} tracks",
        "add a {n} bar clip on the {track} track",
        "delete the selected clip",
        "rename the clip to {genre} loop",
        "duplicate the {track} clip",
        "select all clips longer than {n} bars",
        "select the midi clips",
        "quantize the {track} notes to 1/16",
        "transpose the {track} up {n} semitones",
        "set the velocity of the selected notes to 100",
        "set the tempo to {bpm}",
        "move the {track} track to position {n}",
        "create a rack on the {track} track",
        "add {plugin} and {plugin} to {track}",
        "clear the {track} clip",
    ],
    "MUSIC": [
        "suggest a chord progression in {key}",
        "give me a {genre} progression",
        "what chords work in {key}",
        "write a {mood} chord progression",
        "a {genre} ii-V-I please",
        "generate a {n} bar chord loop in {key}",
        "harmonize this melody",
        "reharmonize the progression",
        "come up with a {genre} melody in {key}",
        "suggest some {mood} chords",
        "what's a good progression for a {mood} {genre} track",
        "write a {n} bar melody in {key}",
        "give me chords for a {genre} tune",
        "some {genre} voicings in {key}",
        "extend this progression",
        "suggest a bassline for these chords",
        "what key is this in",
        "give me a {mood} {genre} chord loop",
        "write a counter melody",
        "turn this into a {genre} progression",
        "chords for the {section}",
        "ideas for the {section} harmony",
        "what should the {section} do harmonically",
        "a {mood} progression for the {section}",
        "rework the {section} chords",
    ],
    "BOTH": [
        "create a {inst} track with a {genre} chord progression",
        "make a new {inst} track and write a {mood} progression on it",
        "add a {genre} bassline to the {track} track",
        "put a {n} bar {genre} loop on the {track} track",
        "write some {key} chords on the {track} track",
        "create a {track} track and add a {genre} melody",
        "add a melody to the {track} track",
        "new {inst} track with a {n} bar progression in {key}",
        "make a {inst} track and put a {mood} loop on it",
        "add {n} bars of {genre} chords to {track}",
        "create a pad track with a {mood} progression",
        "write a {genre} bassline on a new bass track",
        "put a {key} progression on the {track} track",
        "make a {inst} track playing a {genre} riff",
        "write the {section} chords on the {track} track",
        "new {inst} track with a {section} melody",
    ],
    "AUTOMATION": [
        "automate the {param} with a {shape} over {n} bars",
        "draw a {shape} lfo on the {param}",
        "create an {n} bar {param} automation clip",
        "sweep the {param} up over {n} bars",
        "fade the volume out over the last {n} bars",
        "tremolo on the {track} volume",
        "add a {shape} lfo to the {param} on {track}",
        "move the selected automation clip to bar {bar}",
        "loop the automation clip",
        "clear the automation on the {track} track",
        "duplicate the automation clip",
        "resize the automation clip to {n} bars",
        "automate the {param} from 0 to 1 over {n} bars",
        "make the {param} pulse every beat",
        "rename the automation clip to {genre} sweep",
        "draw {n} cycles of a {shape} on the {param}",
        "ramp the {param} down over the {n} bar section",
        "freeform automation on the {param}: start at 0, jump to 1 at beat 2",
        "open the {param} up across the {section}",
        "automate the {param} through the {section}",
        "clear the curves off the {section}",
    ],
    "DRUM": [
        "write a {genre} drum beat",
        "make a {genre} groove at {bpm} bpm",
        "add a fill at the end",
        "make the {drumpart} busier",
        "four on the floor {drumpart} pattern",
        "add ghost notes on the {drumpart}",
        "humanize the drums",
        "swing the {drumpart}",
        "give me a breakbeat",
        "sparser {drumpart} pattern",
        "add a {drumpart} on the offbeat",
        "double time the {drumpart}",
        "write a {n} bar {genre} beat",
        "make the beat more {mood}",
        "add a {drumpart} roll before the drop",
        "simplify the drum pattern",
        "put the {drumpart} on every 16th",
        "make a {genre} drum loop at {bpm}",
        "vary the second bar of the beat",
        "add some percussion to the groove",
        "thin out the {drumpart} in the {section}",
        "busier drums for the {section}",
        "write the {section} beat",
        "drop the {drumpart} out in the {section}",
    ],
    "MIXING": [
        "why does my mix sound muddy",
        "how is my gain staging",
        "is the low end too heavy",
        "what should I fix in this mix",
        "analyze my mix",
        "is anything clipping",
        "how is the stereo width",
        "should I compress the {track} bus",
        "my mix sounds harsh, what do I do",
        "give me mixing feedback",
        "check the levels",
        "is the {track} too loud",
        "how do I make the mix louder",
        "the {track} is fighting the {drumpart}, what should I do",
        "does the mix translate to small speakers",
        "how much headroom do I have",
        "what is masking the {track}",
        "is my mix balanced",
        "review the mix",
        "how is the dynamic range",
        "the {track} is buried in the {section}",
        "the {section} feels thin compared to the rest",
        "why does the {section} sound so different",
    ],
    "SESSION": [
        "launch scene {scene}",
        "fire scene {scene}",
        "stop all clips",
        "stop the {track} clip",
        "play scene {scene}",
        "trigger the {track} clip",
        "record a new scene",
        "start the session",
        "stop the session",
        "arm the {track} track for recording",
        "launch the {scene} scene",
        "queue scene {scene}",
        "capture what I just played into a new scene",
        "stop everything",
        "trigger clip {n} on the {track} track",
        "loop the {scene} scene",
    ],
}
