"""Japanese template bank (same POOLS/TEMPLATES contract as seeds_en).

Curated rather than machine-translated, following the command POC's rule that
localized seeds are hand-checked and small; volume comes from expanding them
against the pools. DAW vocabulary is katakana-first because that is what the
Japanese UI and Japanese producers actually use (トラック, クオンタイズ), with
kanji verbs for the actions (作成/削除/追加).

Note the tokenizer emits one token per kana/kanji, so these read to the model
as character sequences — which is exactly why MAX_LEN is 32 rather than the
command model's 24.
"""
from __future__ import annotations

POOLS = {
    "track": ["ベース", "ドラム", "リード", "パッド", "ボーカル", "キック",
              "スネア", "ハイハット", "ギター", "シンセ", "ピアノ", "ストリングス",
              "パーカッション", "サブベース"],
    "inst": ["ピアノ", "ベース", "ギター", "シンセ", "ローズ", "オルガン",
             "ストリングス", "パッド", "リード"],
    "key": ["Cメジャー", "Aマイナー", "Dマイナー", "Fメジャー", "Gマイナー",
            "Eマイナー", "Bbメジャー", "F#マイナー"],
    "genre": ["ジャズ", "ブルース", "ハウス", "テクノ", "ローファイ", "ネオソウル",
              "ファンク", "トラップ", "アンビエント", "ロック", "ポップ",
              "ドラムンベース", "ボサノバ", "ディスコ"],
    "mood": ["ダークな", "明るい", "切ない", "壮大な", "落ち着いた", "幻想的な"],
    "param": ["フィルターカットオフ", "カットオフ", "レゾナンス", "ボリューム",
              "パン", "リバーブセンド", "ディレイ", "ドライブ"],
    "shape": ["サイン波", "三角波", "ノコギリ波", "矩形波", "ランダム"],
    "n": ["1", "2", "4", "8", "16"],
    "bar": ["1", "2", "3", "5", "9"],
    "scene": ["1", "2", "3", "4", "イントロ", "バース", "コーラス", "ドロップ"],
    # Shared across classes on purpose — see the note in seeds_en.POOLS.
    "section": ["イントロ", "Aメロ", "Bメロ", "サビ", "ドロップ", "アウトロ",
                "ブレイク", "2番"],
    "drumpart": ["キック", "スネア", "ハイハット", "ライド", "クラップ", "タム",
                 "パーカッション", "シェイカー"],
    "plugin": ["@serum", "@vital", "@ott", "@pro_q_3", "@valhalla", "@1176"],
    "colour": ["赤", "青", "緑", "オレンジ", "紫", "黄色"],
    "db": ["-3", "-6", "-9", "-12", "0"],
    "bpm": ["90", "120", "128", "140", "160", "174"],
}

TEMPLATES = {
    "COMMAND": [
        "{track}トラックを作成",
        "新しい{track}トラックを追加",
        "{track}トラックを作って",
        "{track}トラックを削除",
        "{track}を{inst}に名前変更",
        "{track}をミュート",
        "{track}トラックをソロ",
        "{track}に{plugin}を追加",
        "{track}トラックに{plugin}を入れて",
        "{track}のボリュームを{db}dBにする",
        "{track}を{colour}にする",
        "{track}と{drumpart}のトラックをグループ化",
        "{track}トラックに{n}小節のクリップを追加",
        "選択したクリップを削除",
        "{track}のノートを16分でクオンタイズ",
        "{track}を{n}半音上げる",
        "テンポを{bpm}にする",
        "{track}トラックにラックを作成",
        "{track}のパンを左に振って",
        "クリップの名前を{genre}ループに変更",
        "{track}トラックを{n}番目に移動",
        "{track}トラックのミュートを解除",
    ],
    "MUSIC": [
        "{key}のコード進行を提案して",
        "{genre}の進行をちょうだい",
        "{key}で使えるコードは",
        "{mood}コード進行を書いて",
        "{n}小節のコードループを{key}で作って",
        "このメロディーにハーモニーをつけて",
        "{genre}のメロディーを{key}で考えて",
        "{mood}コードをいくつか提案して",
        "リハーモナイズして",
        "{genre}のボイシングを教えて",
        "ベースラインのアイデアをちょうだい",
        "この進行を延長して",
        "{key}のスケールに合うコードは",
        "{mood}{genre}の進行を作って",
        "これは何のキー",
        "{section}のコードを考えて",
        "{section}のハーモニーのアイデア",
        "{section}を{mood}進行にしたい",
    ],
    "BOTH": [
        "{inst}トラックを作って{genre}のコード進行を書いて",
        "新しい{inst}トラックに{mood}進行を入れて",
        "{track}トラックに{genre}のベースラインを追加",
        "{track}トラックに{n}小節の{genre}ループを置いて",
        "{track}トラックに{key}のコードを書いて",
        "{track}トラックを作って{genre}のメロディーを追加",
        "新しい{inst}トラックに{key}の進行を{n}小節",
        "{track}トラックにメロディーを追加して",
        "{inst}トラックを新規作成して{mood}ループを入れて",
    ],
    "AUTOMATION": [
        "{param}を{shape}で{n}小節オートメーション",
        "{param}に{shape}のLFOを描いて",
        "{n}小節の{param}オートメーションクリップを作成",
        "{param}を{n}小節かけて上げて",
        "最後の{n}小節でボリュームをフェードアウト",
        "{track}のボリュームにトレモロ",
        "選択したオートメーションクリップを{bar}小節目に移動",
        "オートメーションクリップをループ",
        "{track}トラックのオートメーションを消して",
        "オートメーションクリップを{n}小節にリサイズ",
        "{param}を0から1まで{n}小節で動かして",
        "{param}を{n}周期の{shape}で揺らして",
        "オートメーションクリップを複製",
        "{section}で{param}を開いていって",
        "{section}のオートメーションを消して",
    ],
    "DRUM": [
        "{genre}のドラムビートを書いて",
        "{bpm}で{genre}のグルーヴを作って",
        "最後にフィルを入れて",
        "{drumpart}をもっと細かく",
        "四つ打ちの{drumpart}パターン",
        "{drumpart}にゴーストノートを追加",
        "ドラムをヒューマナイズ",
        "{drumpart}にスウィングをかけて",
        "ブレイクビートをちょうだい",
        "{drumpart}のパターンをシンプルに",
        "裏拍に{drumpart}を追加",
        "{n}小節の{genre}ビートを書いて",
        "ドラムループを{bpm}で作って",
        "ドラムパターンに変化をつけて",
        "{drumpart}を16分で刻んで",
        "{section}のドラムを書いて",
        "{section}で{drumpart}を抜いて",
        "{section}のビートをもっと細かく",
    ],
    "MIXING": [
        "ミックスが濁っている理由は",
        "ゲインステージングはどう",
        "低域が重すぎる",
        "このミックスで直すべきところは",
        "ミックスを分析して",
        "クリップしているところある",
        "ステレオの広がりはどう",
        "{track}バスをコンプすべき",
        "ミックスが耳に痛い、どうすれば",
        "ミックスのフィードバックをちょうだい",
        "レベルをチェックして",
        "{track}が大きすぎる",
        "ヘッドルームはどれくらい",
        "ミックスのバランスはどう",
        "{track}がマスクされている",
        "ミックスをレビューして",
        "{track}の音量バランスはどう",
        "{track}と{drumpart}がぶつかってる",
        "{genre}っぽいミックスにするには",
        "低域と高域のバランスを見て",
        "{track}のEQはこれでいい",
        "マスターのラウドネスはどれくらい",
        "位相の問題ある",
        "{track}をもっと前に出すには",
        "{track}にコンプは必要",
        "ミックスがモノで崩れる",
        "{section}で{track}が埋もれる",
        "{section}だけ音が細い",
    ],
    "SESSION": [
        "シーン{scene}を再生",
        "シーン{scene}を起動",
        "全てのクリップを停止",
        "{track}のクリップを止めて",
        "新しいシーンを録音",
        "セッションを開始",
        "セッションを停止",
        "{track}トラックを録音待機",
        "シーン{scene}をキューに入れて",
        "全部止めて",
        "{track}トラックのクリップを再生",
        "シーン{scene}をループ",
        "{track}トラックのクリップをトリガー",
        "シーン{scene}に切り替えて",
        "次のシーンを準備して",
        "{track}のクリップをキューに入れて",
        "録音を開始",
        "シーン{scene}を停止",
        "{track}トラックの録音待機を解除",
        "今弾いたのをシーンに取り込んで",
    ],
}
