"""Export the trained intent+slots model to C++ inference artifacts.

One-off codegen: reads the Brevitas checkpoint (model.pt) + maps.json and emits
the plain-float32 weights, vocab/intent/tag lookup tables, and a parity fixture
into the app tree so the hand-written C++ backend (magda/agents/command_model.*)
can run the model offline with zero new dependencies.

CPU path is float32: the 4-bit quantization only matters for the FINN/FPGA
export, so we dequantize to the float master weights here. Empirically the
float forward reproduces the gold DSL on 102/102 of the committed test set
(the quantized forward is 101/102), so float is both simpler and strictly the
better reference for the CPU backend.

    ./.venv/bin/python -m model.export_cpp

Regenerate whenever the checkpoint or maps change. Outputs are committed.
"""
from __future__ import annotations

import json
import os

import torch
import torch.nn.functional as F

from dataset.tagging import reconstruct
from magda_dsl import dsl
from model.data import MAX_LEN, encode_text, load_maps

HERE = os.path.dirname(os.path.abspath(__file__))
POC = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(POC))
ARTIFACTS = os.path.join(HERE, "artifacts")

AGENTS_DIR = os.path.join(REPO, "magda", "agents")
TESTS_DIR = os.path.join(REPO, "tests")

DILATIONS = (1, 2, 4)


def _fmt(x: float) -> str:
    """9 significant digits round-trips a float32 exactly."""
    return "%.9g" % float(x)


def _wrap(values, per_line: int) -> str:
    lines = []
    for i in range(0, len(values), per_line):
        lines.append("    " + ", ".join(values[i:i + per_line]) + ",")
    return "\n".join(lines)


def _float_array(name: str, flat) -> str:
    body = _wrap([_fmt(v) for v in flat], 200)
    return f"const float {name}[] = {{\n{body}\n}};\n\n"


def _cstr(s: str) -> str:
    out = (s.replace("\\", "\\\\").replace('"', '\\"')
            .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t"))
    return '"' + out + '"'


def _string_array(name: str, items) -> str:
    body = _wrap([_cstr(s) for s in items], 20)
    return f"const char* const {name}[] = {{\n{body}\n}};\n\n"


def load_reference():
    """Plain-float forward that mirrors the C++ backend, used to render the
    parity fixture. Identical math to command_model.cpp: pad to MAX_LEN,
    convolve the full padded sequence, mean-pool / slot-argmax over [0, L)."""
    vocab, intents, tags = load_maps(os.path.join(ARTIFACTS, "maps.json"))
    id2intent = {v: k for k, v in intents.items()}
    id2tag = {v: k for k, v in tags.items()}
    ck = torch.load(os.path.join(ARTIFACTS, "model.pt"), map_location="cpu")
    sd = ck["state_dict"]

    emb = sd["embed.weight"]
    w1, b1 = sd["b1.0.weight"], sd["b1.0.bias"]
    w2, b2 = sd["b2.0.weight"], sd["b2.0.bias"]
    w3, b3 = sd["b3.0.weight"], sd["b3.0.bias"]
    sw, sb = sd["slot_head.weight"], sd["slot_head.bias"]
    iw, ib = sd["intent_head.weight"], sd["intent_head.bias"]

    def predict(text):
        toks, ids, L = encode_text(text, vocab)
        if L == 0:
            return ""
        with torch.no_grad():
            e = F.embedding(ids, emb).transpose(1, 2)
            h = F.relu(F.conv1d(e, w1, b1, padding=1, dilation=1))
            h = F.relu(F.conv1d(h, w2, b2, padding=2, dilation=2))
            h = F.relu(F.conv1d(h, w3, b3, padding=4, dilation=4))
            slot = F.linear(h.transpose(1, 2), sw, sb)[0]
            pooled = h[0][:, :L].mean(1, keepdim=True).transpose(0, 1)
            intent_logits = F.linear(pooled, iw, ib)[0]
        intent = id2intent[int(intent_logits.argmax(-1))]
        tag_ids = slot.argmax(-1)[:L].tolist()
        tag_names = [id2tag[t] for t in tag_ids]
        try:
            return dsl.render(reconstruct(intent, toks[:L], tag_names))
        except Exception:
            return ""

    return vocab, intents, tags, sd, predict


def export():
    vocab, intents, tags, sd, predict = load_reference()

    id2tok = [None] * len(vocab)
    for tok, i in vocab.items():
        id2tok[i] = tok
    id2intent = [None] * len(intents)
    for name, i in intents.items():
        id2intent[i] = name
    id2tag = [None] * len(tags)
    for name, i in tags.items():
        id2tag[i] = name

    embed = sd["embed.weight"].shape[1]
    hidden = sd["b1.0.weight"].shape[0]

    # ---- data header -----------------------------------------------------
    hpp = f"""// GENERATED by prototypes/command-model-poc/model/export_cpp.py — do not edit.
// Dequantized float32 weights + lookup tables for the tiny command model.
#pragma once

namespace magda::cmdmodel::data {{

inline constexpr int kVocabSize = {len(vocab)};
inline constexpr int kEmbed = {embed};
inline constexpr int kHidden = {hidden};
inline constexpr int kNumIntents = {len(intents)};
inline constexpr int kNumTags = {len(tags)};
inline constexpr int kMaxLen = {MAX_LEN};
inline constexpr int kKernel = 3;

extern const float kEmbedWeight[];    // [kVocabSize * kEmbed]
extern const float kB1Weight[];       // [kHidden * kEmbed * kKernel]
extern const float kB1Bias[];         // [kHidden]
extern const float kB2Weight[];       // [kHidden * kHidden * kKernel]
extern const float kB2Bias[];         // [kHidden]
extern const float kB3Weight[];       // [kHidden * kHidden * kKernel]
extern const float kB3Bias[];         // [kHidden]
extern const float kSlotWeight[];     // [kNumTags * kHidden]
extern const float kSlotBias[];       // [kNumTags]
extern const float kIntentWeight[];   // [kNumIntents * kHidden]
extern const float kIntentBias[];     // [kNumIntents]

extern const char* const kVocab[];    // [kVocabSize]  id -> token
extern const char* const kIntents[];  // [kNumIntents] id -> intent name
extern const char* const kTags[];     // [kNumTags]    id -> BIO tag name

}}  // namespace magda::cmdmodel::data
"""
    with open(os.path.join(AGENTS_DIR, "command_model_data.hpp"), "w") as f:
        f.write(hpp)

    # ---- data source -----------------------------------------------------
    def flat(name):
        return sd[name].detach().flatten().tolist()

    cpp = ['// GENERATED by prototypes/command-model-poc/model/export_cpp.py — do not edit.\n',
           "// clang-format off\n",  # keep the weight blob compact (LOC policy)
           '#include "command_model_data.hpp"\n\n',
           "namespace magda::cmdmodel::data {\n\n"]
    cpp.append(_float_array("kEmbedWeight", flat("embed.weight")))
    cpp.append(_float_array("kB1Weight", flat("b1.0.weight")))
    cpp.append(_float_array("kB1Bias", flat("b1.0.bias")))
    cpp.append(_float_array("kB2Weight", flat("b2.0.weight")))
    cpp.append(_float_array("kB2Bias", flat("b2.0.bias")))
    cpp.append(_float_array("kB3Weight", flat("b3.0.weight")))
    cpp.append(_float_array("kB3Bias", flat("b3.0.bias")))
    cpp.append(_float_array("kSlotWeight", flat("slot_head.weight")))
    cpp.append(_float_array("kSlotBias", flat("slot_head.bias")))
    cpp.append(_float_array("kIntentWeight", flat("intent_head.weight")))
    cpp.append(_float_array("kIntentBias", flat("intent_head.bias")))
    cpp.append(_string_array("kVocab", id2tok))
    cpp.append(_string_array("kIntents", id2intent))
    cpp.append(_string_array("kTags", id2tag))
    cpp.append("}  // namespace magda::cmdmodel::data\n")
    with open(os.path.join(AGENTS_DIR, "command_model_data.cpp"), "w") as f:
        f.write("".join(cpp))

    # ---- parity fixture --------------------------------------------------
    rows = [json.loads(l) for l in open(os.path.join(POC, "eval", "testset.jsonl"),
                                        encoding="utf-8") if l.strip()]
    cases = []
    mism = 0
    for r in rows:
        got = predict(r["input"])
        if dsl.normalize(got) != dsl.normalize(r["output"]):
            mism += 1
            print(f"  float-ref != gold: {r['input']!r}\n    got={got!r}\n    gold={r['output']!r}")
        cases.append((r["input"], got))

    fx = ['// GENERATED by prototypes/command-model-poc/model/export_cpp.py — do not edit.\n',
          "// Reference DSL from the Python float32 forward over the committed 102-case\n",
          "// test set. The C++ backend must reproduce each string byte-for-byte.\n",
          "#pragma once\n\n",
          "namespace magda::cmdmodel::test {\n\n",
          "struct ParityCase { const char* input; const char* expected; };\n\n",
          "inline const ParityCase kParityCases[] = {\n"]
    for inp, out in cases:
        fx.append(f"    {{{_cstr(inp)}, {_cstr(out)}}},\n")
    fx.append("};\n\n")
    fx.append(f"inline constexpr int kNumParityCases = {len(cases)};\n\n")
    fx.append("}  // namespace magda::cmdmodel::test\n")
    with open(os.path.join(TESTS_DIR, "command_model_parity_cases.hpp"), "w") as f:
        f.write("".join(fx))

    print(f"exported: {len(vocab)} vocab, {len(intents)} intents, {len(tags)} tags")
    print(f"parity fixture: {len(cases)} cases, {mism} float-ref/gold mismatches")


if __name__ == "__main__":
    export()
