// GENERATED by prototypes/command-model-poc/model/export_cpp.py — do not edit.
// Dequantized float32 weights + lookup tables for the tiny command model.
#pragma once

namespace magda::cmdmodel::data {

inline constexpr int kVocabSize = 281;
inline constexpr int kEmbed = 48;
inline constexpr int kHidden = 64;
inline constexpr int kNumIntents = 34;
inline constexpr int kNumTags = 18;
inline constexpr int kMaxLen = 24;
inline constexpr int kKernel = 3;

extern const float kEmbedWeight[];   // [kVocabSize * kEmbed]
extern const float kB1Weight[];      // [kHidden * kEmbed * kKernel]
extern const float kB1Bias[];        // [kHidden]
extern const float kB2Weight[];      // [kHidden * kHidden * kKernel]
extern const float kB2Bias[];        // [kHidden]
extern const float kB3Weight[];      // [kHidden * kHidden * kKernel]
extern const float kB3Bias[];        // [kHidden]
extern const float kSlotWeight[];    // [kNumTags * kHidden]
extern const float kSlotBias[];      // [kNumTags]
extern const float kIntentWeight[];  // [kNumIntents * kHidden]
extern const float kIntentBias[];    // [kNumIntents]

extern const char* const kVocab[];    // [kVocabSize]  id -> token
extern const char* const kIntents[];  // [kNumIntents] id -> intent name
extern const char* const kTags[];     // [kNumTags]    id -> BIO tag name

}  // namespace magda::cmdmodel::data
