// GENERATED by prototypes/router-model-poc/router/export_cpp.py — do not edit.
// Float32 weights + lookup tables for the on-device ConsoleIntent router.
#pragma once

namespace magda::routermodel::data {

inline constexpr int kVocabSize = 1419;
inline constexpr int kEmbed = 32;
inline constexpr int kHidden = 48;
inline constexpr int kNumLabels = 7;
inline constexpr int kMaxLen = 32;
inline constexpr int kKernel = 3;

extern const float kEmbedWeight[];  // [kVocabSize * kEmbed]
extern const float kB1Weight[];     // [kHidden * kEmbed * kKernel]
extern const float kB1Bias[];       // [kHidden]
extern const float kB2Weight[];     // [kHidden * kHidden * kKernel]
extern const float kB2Bias[];       // [kHidden]
extern const float kB3Weight[];     // [kHidden * kHidden * kKernel]
extern const float kB3Bias[];       // [kHidden]
extern const float kHeadWeight[];   // [kNumLabels * kHidden]
extern const float kHeadBias[];     // [kNumLabels]

extern const char* const kVocab[];   // [kVocabSize] id -> token (UTF-8)
extern const char* const kLabels[];  // [kNumLabels] id -> ConsoleIntent token

}  // namespace magda::routermodel::data
